# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/posts
Accept: application/json

###

POST http://127.0.0.1:8000/posts
Content-Type: application/json

{
  "title": "Shazam",
  "content": "Fury Of the Gods",
  "published": true,
  "rating": 1
}

###

GET http://127.0.0.1:8000/posts/3333
Accept: application/json
