# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/posts
Accept: application/json

###

POST http://127.0.0.1:8000/createposts
Content-Type: application/json

{
  "title": "Harry Potter",
  "content": "Harry Potter and the Half Blood Prince",
  "published": true
}
